### ISSUE TITLE
Command Prompt Window Opens and Instantly closes?

### ISSUE THREAD

**Issue by Trilled** [MartB/RETC#19] opened 2018-05-29 19:17 UTC
Hey so i just got a Corsair K55 and i wanted to this. Ive installed CUE2 Version 2.24.50 and i downloaded the automatic verions of RETC but when i launch the “retc-rpc-server-64.exe” the command promp window pops up and instantly disappears or i will just open and stay blank. (Ive tried opening it before and after launching the game) I even reinstalled CUE2 and RETC Installer. Any help?

Edit : I also tried doing it manually, putting the “RzChromaSDK.dll” and “RzChromaSDK64.dll” in my overwatch folder “C:\Program Files (x86)\Overwatch” and making a folder called retc-server and putting the “CUESDK.x64_2015.dll” and “retc-rpc-server-64.exe” files in there and running it before and after the game and same results. I have windows 10 64bit so there shouldnt be a problem.

PS. I do have SDK Enabled in CUE2

**Comment by MartB** [comment] 2018-05-29 19:50
Usually you just have to execute the installer everything else will be done automatically, no need to run anything manually as RETC installs a service when its installed, that keeps it autostarted.

As for overwatch, this could be a duplicate of #17 when i find time i will check out what they broke, i cant promise anything though.

**Comment by MartB** [comment] 2018-05-29 21:34
see #17 
#closed

**Closed as completed by MartB** 2018-05-29 21:34 UTC
Labels: duplicate
